[project]
sdk_version = "0.10.0"
name = "reblue"

[entrypoint]
file_path = "assets/default.xex"
out_directory_path = "generated"
includes = [
  "config/functions.toml",
  "config/hooks/battle_camera_task.toml",
  "config/hooks/battle_task.toml",
  "config/hooks/crt.toml",
  "config/hooks/disc_io.toml",
  "config/hooks/encyclopedia_menu.toml",
  "config/hooks/frame_interp.toml",
  "config/hooks/guest_debug.toml",
  "config/hooks/hud_anchor.toml",
  "config/hooks/hud_fade.toml",
  "config/hooks/iss_event.toml",
  "config/hooks/language.toml",
  "config/hooks/loader.toml",
  "config/hooks/mouse_cursor.toml",
  "config/hooks/output_resolution.toml",
  "config/hooks/physical_buffers.toml",
  "config/hooks/prompt_textures.toml",
  "config/hooks/pso_predictor.toml",
  "config/hooks/render_tweaks.toml",
  "config/hooks/save.toml",
  "config/hooks/script_man_task.toml",
  "config/hooks/shop_mouse.toml",
  "config/hooks/sofdec_player.toml",
  "config/hooks/title_menu.toml",
  "config/hooks/tutorials.toml",
]

setjmp_address = 0x826C5D00
longjmp_address = 0x826C5AB0

skip_lr = true
ctr_as_local = true
xer_as_local = true
cr_as_local = true
reserved_as_local = true
non_volatile_as_local = true

