[[midasm_hook]]
address = 0x821335A4
name = "bdSceneFSAASeedHook"
registers = ["r11"]
after_instruction = true

[[midasm_hook]]
address = 0x82186C40
name = "bdSceneTilingSuppressHook"
registers = []
after_instruction = false
jump_address_on_true = 0x82186C54

[[midasm_hook]]
address = 0x8213307C
name = "bdSceneRenderScaleHook"
registers = ["r31"]
after_instruction = true

[[midasm_hook]]
address = 0x82178670
name = "bdReflectionResolutionScaleHook"
registers = ["r31"]
after_instruction = false

[[midasm_hook]]
address = 0x821876A4
name = "bdReflectionSurfaceTagHook"
registers = ["r3"]
after_instruction = true

[[midasm_hook]]
address = 0x821876E0
name = "bdReflectionSurfaceTagHook"
registers = ["r3"]
after_instruction = true

[[midasm_hook]]
address = 0x821786D0
name = "bdReflectionSurfaceTagHook"
registers = ["r3"]
after_instruction = true

[[midasm_hook]]
address = 0x821871E4
name = "bdShadowResolutionScaleHook"
registers = ["r3", "r4"]
after_instruction = false

[[midasm_hook]]
address = 0x8217517C
name = "bdShadowResolutionScaleHook"
registers = ["r3", "r4"]
after_instruction = false

[[midasm_hook]]
address = 0x82175974
name = "bdShadowCoverageScaleHook"
registers = ["f1"]
after_instruction = false

[[midasm_hook]]
address = 0x82142FAC
name = "bdCameraRefractionUvScaleHook"
registers = ["r11"]
after_instruction = false

[[midasm_hook]]
address = 0x8213d034
name = "bdCameraRefractionUvScaleHook"
registers = ["r11"]
after_instruction = false

[[midasm_hook]]
address = 0x8213d18c
name = "bdMotionBlurQuadInsetHook"
registers = ["r5"]
after_instruction = false

[[midasm_hook]]
address = 0x82217224
name = "bdDOFStrengthScaleHook"
registers = ["r11"]
after_instruction = true

[[midasm_hook]]
address = 0x8221515C
name = "bdGaussianBlurTapStepHook"
registers = ["f0", "f13", "r28"]
after_instruction = false

[[midasm_hook]]
address = 0x82215B28
name = "bdBloomBlurTapStepHook"
registers = ["f0", "f13"]
after_instruction = false

[[midasm_hook]]
address = 0x8221B360
name = "bdBloomTargetSizeHook"
registers = ["r4", "r5"]
after_instruction = true

[[midasm_hook]]
address = 0x8221B38C
name = "bdBloomTargetSizeHook"
registers = ["r4", "r5"]
after_instruction = true

[[midasm_hook]]
address = 0x824547B0
name = "bdWaterSpecIntensityClampHook"
registers = ["r3"]
after_instruction = false

[[midasm_hook]]
address = 0x824547B8
name = "bdWaterSpecIntensityClampHook"
registers = ["r3"]
after_instruction = false

[[midasm_hook]]
address = 0x8227FBD4
name = "bdFurShellConstantsDirtyHook"
registers = []
after_instruction = false

[[midasm_hook]]
address = 0x82146478
name = "bdPrimBeginDropWarnHook"
registers = ["f31"]
after_instruction = false

[[midasm_hook]]
address = 0x8221914C
name = "bdNtscFilterNoiseDisableHook"
registers = []
after_instruction = false
jump_address_on_true = 0x822191A0
