/**
 * @file    engine/engine.h
 * @copyright Copyright (c) 2026 Tom Clay <tomc@tctechstuff.com>
 *            All rights reserved.
 * @license   BSD 3-Clause License
 *            See LICENSE file in the project root for full license text.
 */
#pragma once

#include "engine/achievements/achievements.h"
#include "engine/action_map.h"
#include "engine/battle_camera_task.h"
#include "engine/battle_task.h"
#include "engine/chara.h"
#include "engine/config.h"
#include "engine/d2anime/d2anime.h"
#include "engine/effect_names.h"
#include "engine/ene_task.h"
#include "engine/events.h"
#include "engine/field_player_entity.h"
#include "engine/frame_clock.h"
#include "engine/frame_interp.h"
#include "engine/game.h"
#include "engine/game_options.h"
#include "engine/game_task.h"
#include "engine/game_text.h"
#include "engine/gimmicks.h"
#include "engine/hud_fade.h"
#include "engine/input/action_state.h"
#include "engine/input/actions.h"
#include "engine/input/binding_store.h"
#include "engine/input/button_map.h"
#include "engine/input/input_sources.h"
#include "engine/iss_event.h"
#include "engine/item_save_data.h"
#include "engine/language.h"
#include "engine/loader.h"
#include "engine/menus/menus.h"
#include "engine/mini_map_task.h"
#include "engine/play_record.h"
#include "engine/ply_task.h"
#include "engine/save/save.h"
#include "engine/scene_file.h"
#include "engine/script.h"
#include "engine/script_man_task.h"
#include "engine/script_vars.h"
#include "engine/sequence_control.h"
#include "engine/settings.h"
#include "engine/simple_status_task.h"
#include "engine/sofdec_player.h"
#include "engine/stat_breakdown.h"
#include "engine/state_layout.h"
#include "engine/task.h"
#include "engine/virtual_buttons.h"
#include "engine/visual_render.h"
