# Invoked by reblue_bin2c via `cmake -P`. Reads INPUT as hex bytes and writes
# <STEM>.h / <STEM>.cpp declaring <SYMBOL>_size and <SYMBOL>_data[].

if(NOT DEFINED INPUT OR NOT DEFINED SYMBOL OR NOT DEFINED STEM)
    message(FATAL_ERROR "bin2c_run.cmake requires -DINPUT, -DSYMBOL, -DSTEM")
endif()

file(READ "${INPUT}" _hex HEX)
file(SIZE "${INPUT}" _size)

# Turn "aabbcc..." into "0xaa,0xbb,0xcc,..." on one long line. Compilers are
# fine with long lines; readability doesn't matter for a generated artefact.
string(REGEX REPLACE "(..)" "0x\\1," _bytes "${_hex}")

get_filename_component(_header_name "${STEM}" NAME)

file(WRITE "${STEM}.h"
"// Generated by cmake/bin2c_run.cmake - do not edit.\n"
"#pragma once\n"
"#include <cstddef>\n"
"#include <cstdint>\n"
"\n"
"extern const size_t  ${SYMBOL}_size;\n"
"extern const uint8_t ${SYMBOL}_data[];\n")

file(WRITE "${STEM}.cpp"
"// Generated by cmake/bin2c_run.cmake - do not edit.\n"
"#include \"${_header_name}.h\"\n"
"\n"
"const size_t  ${SYMBOL}_size = ${_size};\n"
"const uint8_t ${SYMBOL}_data[] = {${_bytes}};\n")
