name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  actions: write

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      publish_mode: release
    secrets: inherit
